baseURL = "https://poisson.math.umb.edu/umbibio/"
languageCode = "en-us"
title = "UMBIBIO Weekly Talks"
theme = "learn"
relativeURLs = false

[params]
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "mine"
  sort = "name"
